### ISSUE TITLE
uuid not pip installable

### ISSUE THREAD

**Issue by AdyenPedro** [adyen-examples/adyen-python-online-payments#14]
I have had an issue where I was not able to install uuid via pip install... however, I was able to remove the uuid line from requirements.txt, and everything was then completely fine when running the the setup.sh. It appears uuid may be included with Python anyway.

The error from setup.sh:

Could not find a version that satisfies the requirement uuid==1.30 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for uuid==1.30 (from -r requirements.txt (line 3))

**Comment by gcatanese** [comment]
@AdyenPedro I have dropped the module, thank you for flagging this
