### ISSUE TITLE
Adyen JS Encryption.

### ISSUE THREAD

**Issue by KhushC-03** [adyen-examples/adyen-python-online-payments#6]
Is there a way of using this library to encrypt the payment data of my client? E.g expiry date and cvv.

**Comment by deepu105** [comment]
Unfortunately no. We don't expose the encryption part due to security
reasons. Its advisobale to use the Adyen components to do the encryption

Thanks & Regards,
Deepu

**Comment by KhushC-03** [comment]
Oh right, is there no way of performing the Adyen JS encryption in Python?

**Comment by deepu105** [comment]
We use standard CSE encryption so you could probably replicate that but we
cannot assure support or do we recommend that due to security requirements

**Comment by gcatanese** [comment]
Closing the issue: Adyen components (and backend) take care of safely encrypting data making unnecessary to perform your own encryption on top.
